steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/my-project-newcicd/helloworld-image', '.' ]
images:
- 'gcr.io/my-project-newcicd/helloworld-image'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  timeout: '1600s'
